export const STATUSES = ["pending", "processing", "done"];
export const PRIORITIES = ["low", "medium", "high"];

export const STATUS_CLASSES = {
  pending: "bg-light",
  processing: "bg-warning",
  done: "bg-success",
};

export const PRIORITY_CLASSES = {
  low: "success",
  // low: "info",
  // low: "bg-info",
  medium: "warning",
  // medium: "primary",
  // medium: "bg-primary",
  high: "danger",
  // high: "danger",
  // high: "bg-danger",
};

export const todoData = [
  {
    id: 1,
    title: "Analyze project requirements",
    status: "done",
    priority: "high",
    owner: "Alice",
    createdAt: "2025-01-05T09:15",
    startedAt: "2025-01-06T10:00",
    finishedAt: "2025-01-07T16:30",
  },
  {
    id: 2,
    title: "Design user interface (UI)",
    status: "processing",
    priority: "high",
    owner: "Bob",
    createdAt: "2025-01-07T10:00",
    startedAt: "2025-01-08T09:30",
    finishedAt: null,
  },
  {
    id: 3,
    title: "Set up React project structure",
    status: "done",
    priority: "medium",
    owner: "Charlie",
    createdAt: "2025-01-08T11:30",
    startedAt: "2025-01-08T12:00",
    finishedAt: "2025-01-09T14:00",
  },
  {
    id: 4,
    title: "Develop Todo component",
    status: "processing",
    priority: "medium",
    owner: "Alice",
    createdAt: "2025-01-10T08:45",
    startedAt: "2025-01-10T09:00",
    finishedAt: null,
  },
  {
    id: 5,
    title: "Separate logic from UI using Hooks",
    status: "pending",
    priority: "high",
    owner: "Bob",
    createdAt: "2025-01-12T14:20",
    startedAt: null,
    finishedAt: null,
  },
  {
    id: 6,
    title: "Add task filtering by status",
    status: "pending",
    priority: "medium",
    owner: "Charlie",
    createdAt: "2025-01-13T11:10",
    startedAt: null,
    finishedAt: null,
  },
  {
    id: 7,
    title: "Improve user experience (UX)",
    status: "pending",
    priority: "low",
    owner: "Alice",
    createdAt: "2025-01-15T09:50",
    startedAt: null,
    finishedAt: null,
  },
  {
    id: 8,
    title: "Test application and fix bugs",
    status: "pending",
    priority: "high",
    owner: "Bob",
    createdAt: "2025-01-16T13:25",
    startedAt: null,
    finishedAt: null,
  },
  {
    id: 9,
    title: "Prepare project for deployment",
    status: "pending",
    priority: "medium",
    owner: "Charlie",
    createdAt: "2025-01-18T10:40",
    startedAt: null,
    finishedAt: null,
  },
];

